### ISSUE TITLE
Example LLM Promopts From Customer

### ISSUE THREAD

**Issue by GiovanniL19** [Reboot-London-2024/Ctrl-Alt-Elite#2]
Please write a list of prompts customer might say/wright in app.

**Comment by rachel27-2** [comment]
1. I want to give my daughter access to help manage my accounts because I find it difficult to use online banking. She should be able to pay my bills and transfer money, but not make any major changes to my account settings.
2. I need my caregiver to have access to my account to pay for my medical expenses and other bills. They shouldn't be able to change my personal details or open new accounts.
3. My son needs to help me with my banking because I'm not comfortable with computers. He should be able to view my account balances and transactions, and also transfer money if needed.
4. I want my social worker to help manage my finances. They should be able to view my transactions and pay my bills, but they shouldn't be able to modify my account settings or personal information.
5. I am currently unwell and need my friend to handle my banking for me. They should be able to transfer money, pay bills, and view transactions, but not change any account details.
6. I find online banking confusing and would like my nephew to help me. He should be able to check my balance and make payments, but not change my account settings.
7. I want my legal power of attorney to have full access to my accounts to manage my finances as I am unable to do so myself.
8. I had surgery and need my neighbor to handle my banking for a few months. They should be able to view transactions and transfer funds but not change my account settings permanently.
9. My daughter speaks English better than I do, so I need her to help with my banking. She should be able to view my account and make transfers but not change any important settings.
10. I have memory issues and need my grandson to keep an eye on my account to make sure everything is in order. He should be able to view my transactions and pay bills, but not change my account information.

These ones are less specific and focus more on customer situation and needs:
1. My elderly mother is having difficulty managing her bank accounts online. She often gets confused by the technology and struggles to keep track of her finances. She needs me to help her with everyday banking tasks like checking her account balances, keeping an eye on her transactions, and ensuring her bills are paid on time.
2. Due to my disability, I find it challenging to manage my finances. My caregiver assists me with day-to-day activities, and I need them to help handle my banking. This includes paying for my medical expenses, managing my bills, and ensuring my financial matters are in order since I can't do this easily myself.
3. I'm not very comfortable using computers or smartphones for online banking. My son usually helps me with these tasks. He assists me with logging into my account, understanding my transactions, and making sure that all my financial activities are properly managed because I find the technology overwhelming.
4. As someone who struggles with managing my own finances, I rely on my social worker to help me. They need to keep track of my spending, ensure my bills are paid, and manage other financial responsibilities. I trust them to handle these tasks as part of their role in supporting me.
5. I am currently recovering from a serious illness, which makes it difficult for me to manage my finances. I need my friend to take care of my banking needs during this time. They would need to handle things like paying my bills, transferring money, and keeping an eye on my account while I'm unable to do so.
6. Online banking is very confusing for me, and I often make mistakes. My nephew has always been more tech-savvy and helps me out. He assists me with understanding my bank statements, making sure my bills are paid, and ensuring my financial records are accurate since I struggle with the technology.
7. I have granted my legal power of attorney the authority to manage my finances because I'm unable to do so myself. This person needs to oversee all my financial activities, handle transactions, pay bills, and ensure that my accounts are in good standing, as they are legally responsible for my financial well-being.
8. After my recent surgery, I am temporarily unable to handle my banking. I need my neighbor to help me for a few months until I recover. They will need to take care of paying my bills, managing my accounts, and making sure that my financial obligations are met during this recovery period.
9. English is not my first language, and I often have trouble understanding my bank's website and communications. My daughter, who is fluent in English, helps me navigate these challenges. She assists me with checking my account information, understanding my transactions, and making sure everything is correct.
10. As I age, my memory isn't as reliable as it used to be, and I sometimes forget to pay bills or check my bank statements. My grandson has been helping me keep track of my finances. He ensures that my bills are paid on time, monitors my transactions for any unusual activity, and helps me manage my day-to-day banking needs.
